# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'GSTDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GSTDemo
  pod 'AFNetworking', '~> 3.2.1'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Masonry'
  pod 'YYModel'
  pod 'YYCache'
  pod 'YYCategories'
  pod 'OpenUDID'
  pod 'MJExtension', '~> 3.0.13’
  pod 'YYText'
  pod 'JCore'
  pod 'JPush'
  pod 'Reachability'
  pod 'YHPopupView'
  pod 'YHPhotoKit'
  pod 'FMDB'
  pod 'RxSwift','~> 4.2.0'
  pod 'RxCocoa','~> 4.4.1'
  pod 'BaiduMapKit','~> 4.1.1'
  pod 'SJVideoPlayer'
  pod 'SSZipArchive'
  pod 'AliyunOSSiOS'

  target 'GSTDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GSTDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
